# Generated by Django 5.2.4 on 2025-08-14 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booked_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='api.seat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.screening'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
